name: fetching_state
description: A small package that helps easily to work with UI changes base on the state of fetching remote data
version: 3.0.0
homepage: https://github.com/samderlust/fetching_state

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
